name: Build, Test and Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches: [main]

env:
  BUILD_DIR: build
  PACKAGE_DIR: package
  ARTIFACTS_DIR: artifacts
  PACKAGE_NAME: decorator-app

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      deb_file: ${{ steps.build-pkg.outputs.deb_path }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine package version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          version=${GITHUB_REF#refs/tags/v}
        elif [ -f VERSION ]; then
          version=$(cat VERSION)
        else
          version=$(date +%Y.%m.%d)-$(git rev-parse --short HEAD)
        fi
        echo "version=${version}" >> $GITHUB_OUTPUT
        echo "PACKAGE_VERSION=${version}" >> $GITHUB_ENV
        echo "Using version: ${version}"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          debhelper \
          dh-make \
          dpkg-dev \
          tree
    - name: Configure project
      run: |
        mkdir -p ${{ env.BUILD_DIR }}
        cd ${{ env.BUILD_DIR }}
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Build project
      run: |
        cd ${{ env.BUILD_DIR }}
        make -j$(nproc)
    - name: Run tests
      run: |
        cd ${{ env.BUILD_DIR }}
        [ -f test_Window ] && ./test_Window
        [ -f test_FancyWindow ] && ./test_FancyWindow
        [ -f test_BorderDecorator ] && ./test_BorderDecorator
        [ -f test_ScrollBarDecorator ] && ./test_ScrollBarDecorator
        [ -f test_main ] && ./test_main
    - name: Prepare package structure
      run: |
        mkdir -p ${{ env.PACKAGE_DIR }}/usr/bin
        mkdir -p ${{ env.PACKAGE_DIR }}/DEBIAN
        find ${{ env.BUILD_DIR }} -maxdepth 1 -type f -executable -not -name "*.so" \
          -exec install -Dm755 {} ${{ env.PACKAGE_DIR }}/usr/bin/ \;
    - name: Generate control file
      run: |
        mkdir -p ${{ env.PACKAGE_DIR }}/DEBIAN
        cat <<EOF > ${{ env.PACKAGE_DIR }}/DEBIAN/control
        Package: ${{ env.PACKAGE_NAME }}
        Section: devel
        Priority: optional
        Architecture: amd64
        Maintainer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        Description: Decorator Pattern Implementation
        EOF
    - name: Build .deb package
      id: build-pkg
      run: |
        mkdir -p ${{ env.ARTIFACTS_DIR }}
        DEB_FILE="${{ env.ARTIFACTS_DIR }}/${{ env.PACKAGE_NAME }}_amd64.deb"
        dpkg-deb --build ${{ env.PACKAGE_DIR }} "${DEB_FILE}"
        echo "deb_path=${DEB_FILE}" >> $GITHUB_OUTPUT
        ls -la ${{ env.ARTIFACTS_DIR }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}-deb
        path: ${{ steps.build-pkg.outputs.deb_path }}
        retention-days: 7
      
