name: Build, Test and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential debhelper dh-make dpkg-dev

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ./test_Window
        ./test_FancyWindow
        ./test_BorderDecorator
        ./test_ScrollBarDecorator
        ./test_main

    - name: Create package structure
      run: |
        mkdir -p decorator-package/usr/bin
        mkdir -p decorator-package/DEBIAN
        install -Dm755 build/test_Window decorator-package/usr/bin/
        install -Dm755 build/test_FancyWindow decorator-package/usr/bin/
        install -Dm755 build/test_BorderDecorator decorator-package/usr/bin/
        install -Dm755 build/test_ScrollBarDecorator decorator-package/usr/bin/

    - name: Generate control file
      run: |
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: decorator-app
        Version: 1.0-$(date +%Y%m%d%H%M)
        Section: devel
        Priority: optional
        Architecture: amd64
        Maintainer: CI System <ci@example.com>
        Description: Decorator Pattern Implementation
         Contains the decorator pattern example application and tests.
        EOF

    - name: Verify package structure
      run: |
        tree package
        cat package/DEBIAN/control

    - name: Build .deb package
      run: |
        dpkg-deb --build package
        mkdir -p artifacts
        mv package.deb artifacts/decorator-app_1.0_amd64.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: decorator-package
        path: artifacts/decorator-app_1.0_amd64.deb
        retention-days: 7

    - name: Show package info (debug)
      run: |
        dpkg --info artifacts/decorator-app_1.0_amd64.deb
        dpkg --contents artifacts/decorator-app_1.0_amd64.deb


